twist_mux:
  ros__parameters:
    use_stamped: false

    topics:
      joystick:
        topic: /cmd_vel_joystick  # Joystick outputs are redirected and published to this topic 
        timeout: 0.1
        priority: 100

      mecanum_move:
        topic: /cmd_vel_nexus   # Joystick outputs are redirected and published to this topic 
        timeout: 1.0
        priority: 10
