nexus_twist_node:
  ros__parameters:
    linear_scale: 500.0
    angular_scale: 1.0
    linear_ramp_step: 4.0     # steps to ramp up vx or vy to the target speed
    angular_ramp_step: 0.08   # steps to ramp up w to the target speed

